model:
  model_name: 'Grapher'
  feature_width: 128
  num_layers: 3
  pos_dim: 3
  input_features: 4
  output_features: 4
  batch_norm: True
  act: 'relu'
  global_ratio: 0.25
  global_k: 4
  global_cos: True 
  global_pos: False
  local_nodes: 512
  local_ratio: 0.25
  local_k: 6
  local_cos: False
  local_pos: True
  num_phys: 32
  num_heads: 4

data:
  dataset: 'CarCFD'
  data_path: 'Path_to/car_cfd/'
  train_batchsize: 16
  eval_batchsize: 16
  valid_dir: 1
  test_dir: 0
  normalize: True

train:
  random_seed: 0
  cuda: True
  device: 0
  epochs: 500
  patience: -1
  eval_freq: 1
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.0001

schedule:
  scheduler: 'StepLR'
  step_size: 200
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
