model:
  model_name: 'GNOT'
  branch_size: 1
  output_size: 1
  trunk_size: 3
  space_dim: 3
  n_layers: 3
  n_hidden: 128 
  n_head: 1
  n_inner: 4
  mlp_layers: 3
  attn_type: 'linear'
  act: 'gelu'
  ffn_dropout: 0.0
  attn_dropout: 0.0
  horiz_fourier_dim: 0

data:
  dataset: 'DeformingPlate'
  data_path: 'Path_to/deforming_plate/'
  sample_factor: 1
  train_batchsize: 256
  eval_batchsize: 256
  in_t: 1
  out_t: 1
  duration_t: 10
  normalize: True

train:
  random_seed: 0
  cuda: True
  device: 6
  epochs: 500
  patience: -1
  eval_freq: 1
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100

optimize:
  optimizer: 'Adam'
  lr: 0.001
  weight_decay: 0.0001

schedule:
  scheduler: 'StepLR'
  step_size: 200
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
