model:
  model_name: 'Grapher'
  feature_width: 128
  num_layers: 2
  pos_dim: 3
  input_features: 1
  output_features: 1
  batch_norm: True
  act: 'relu'
  global_ratio: 0.25
  global_k: 4
  global_cos: True 
  global_pos: False
  local_nodes: 128
  local_ratio: 0.25
  local_k: 4
  local_cos: False
  local_pos: True
  num_phys: 32
  num_heads: 8

data:
  dataset: 'DeformingPlate'
  data_path: 'Path_to/deforming_plate/'
  train_batchsize: 128
  eval_batchsize: 128
  in_t: 1
  out_t: 1
  duration_t: 50
  normalize: True

train:
  random_seed: 0
  cuda: True
  device: 0
  epochs: 500
  patience: 50
  eval_freq: 1
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.00001

schedule:
  scheduler: 'StepLR'
  step_size: 200
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
