model:
  model_name: 'UNet'
  in_channels: 1
  out_channels: 1
  init_features: 128
  pos_dim: 2

data:
  dataset: 'Poisson'
  data_path: '/hpc2hdd/home/zli416/jhaidata/DATA/Geo/poisson/poisson_data.pkl'
  train_batchsize: 32
  eval_batchsize: 32
  train_ratio: 0.8
  valid_ratio: 0.1
  test_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'
  graph_type: 'coord'

train:
  random_seed: 0
  cuda: True
  device: 0
  epochs: 500
  patience: 20
  eval_freq: 1
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100

optimize:
  optimizer: 'Adam'
  lr: 0.001
  weight_decay: 0.0001

schedule:
  scheduler: 'StepLR'
  step_size: 200
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
