model:
  model_name: 'UNet'
  in_channels: 1
  out_channels: 1
  init_features: 128
  pos_dim: 2

data:
  dataset: 'NavierStokes'
  data_path: "Path_to/NS/ns_V1e-5_N1200_T20.mat"
  sample_factor: 1
  train_batchsize: 64
  eval_batchsize: 64
  in_t: 1
  out_t: 1
  duration_t: 10
  train_ratio: 0.8
  valid_ratio: 0.1
  test_ratio: 0.1
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 0
  cuda: True
  device: 0
  epochs: 500
  patience: 20
  eval_freq: 1
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100

optimize:
  optimizer: 'Adam'
  lr: 0.001
  weight_decay: 0.0001

schedule:
  scheduler: 'StepLR'
  step_size: 200
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
